name = "clientflow-hub"
compatibility_date = "2024-12-31"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".output/public"

[vars]
ENVIRONMENT = "production"
VITE_API_BASE_URL = "https://clientflow-vjqd.onrender.com"