/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgreementsTokenRouteImport } from './routes/agreements.$token'
import { Route as ApplyTokenRouteImport } from './routes/apply.$token'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as PipelineIndexRouteImport } from './routes/pipeline.index'
import { Route as PipelineIdRouteImport } from './routes/pipeline.$id'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as STokenRouteImport } from './routes/s.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsTokenRoute = AgreementsTokenRouteImport.update({
  id: '/agreements/$token',
  path: '/agreements/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyTokenRoute = ApplyTokenRouteImport.update({
  id: '/apply/$token',
  path: '/apply/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelineRoute,
} as any)
const PipelineIdRoute = PipelineIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PipelineRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProgramsRoute,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/archive': typeof ArchiveRoute
  '/clients': typeof ClientsRouteWithChildren
  '/forms': typeof FormsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/agreements/$token': typeof AgreementsTokenRoute
  '/apply/$token': typeof ApplyTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/s/$token': typeof STokenRoute
  '/clients/': typeof ClientsIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/archive': typeof ArchiveRoute
  '/forms': typeof FormsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/agreements/$token': typeof AgreementsTokenRoute
  '/apply/$token': typeof ApplyTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/s/$token': typeof STokenRoute
  '/clients': typeof ClientsIndexRoute
  '/pipeline': typeof PipelineIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/archive': typeof ArchiveRoute
  '/clients': typeof ClientsRouteWithChildren
  '/forms': typeof FormsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/agreements/$token': typeof AgreementsTokenRoute
  '/apply/$token': typeof ApplyTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/s/$token': typeof STokenRoute
  '/clients/': typeof ClientsIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/archive'
    | '/clients'
    | '/forms'
    | '/intake'
    | '/login'
    | '/monitoring'
    | '/pipeline'
    | '/programs'
    | '/reports'
    | '/review'
    | '/settings'
    | '/agreements/$token'
    | '/apply/$token'
    | '/clients/$clientId'
    | '/pipeline/$id'
    | '/programs/$programId'
    | '/s/$token'
    | '/clients/'
    | '/pipeline/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/archive'
    | '/forms'
    | '/intake'
    | '/login'
    | '/monitoring'
    | '/reports'
    | '/review'
    | '/settings'
    | '/agreements/$token'
    | '/apply/$token'
    | '/clients/$clientId'
    | '/pipeline/$id'
    | '/programs/$programId'
    | '/s/$token'
    | '/clients'
    | '/pipeline'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/archive'
    | '/clients'
    | '/forms'
    | '/intake'
    | '/login'
    | '/monitoring'
    | '/pipeline'
    | '/programs'
    | '/reports'
    | '/review'
    | '/settings'
    | '/agreements/$token'
    | '/apply/$token'
    | '/clients/$clientId'
    | '/pipeline/$id'
    | '/programs/$programId'
    | '/s/$token'
    | '/clients/'
    | '/pipeline/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ArchiveRoute: typeof ArchiveRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  FormsRoute: typeof FormsRoute
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  PipelineRoute: typeof PipelineRouteWithChildren
  ProgramsRoute: typeof ProgramsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  AgreementsTokenRoute: typeof AgreementsTokenRoute
  ApplyTokenRoute: typeof ApplyTokenRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements/$token': {
      id: '/agreements/$token'
      path: '/agreements/$token'
      fullPath: '/agreements/$token'
      preLoaderRoute: typeof AgreementsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$token': {
      id: '/apply/$token'
      path: '/apply/$token'
      fullPath: '/apply/$token'
      preLoaderRoute: typeof ApplyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/pipeline/': {
      id: '/pipeline/'
      path: '/'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/pipeline/$id': {
      id: '/pipeline/$id'
      path: '/$id'
      fullPath: '/pipeline/$id'
      preLoaderRoute: typeof PipelineIdRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface PipelineRouteChildren {
  PipelineIdRoute: typeof PipelineIdRoute
  PipelineIndexRoute: typeof PipelineIndexRoute
}

const PipelineRouteChildren: PipelineRouteChildren = {
  PipelineIdRoute: PipelineIdRoute,
  PipelineIndexRoute: PipelineIndexRoute,
}

const PipelineRouteWithChildren = PipelineRoute._addFileChildren(
  PipelineRouteChildren,
)

interface ProgramsRouteChildren {
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ArchiveRoute: ArchiveRoute,
  ClientsRoute: ClientsRouteWithChildren,
  FormsRoute: FormsRoute,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  PipelineRoute: PipelineRouteWithChildren,
  ProgramsRoute: ProgramsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  AgreementsTokenRoute: AgreementsTokenRoute,
  ApplyTokenRoute: ApplyTokenRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
